### ISSUE TITLE
running on a server, but time does not increase

### ISSUE THREAD

**Issue by SekiBetu** [AlexSterk/TwitchDropGrabber#10]
![image](https://user-images.githubusercontent.com/38283893/114741350-4213d180-9d7d-11eb-88d9-91661a54d5db.png)
i've been running this program for 2 hours, 
(the screenshot is just a sample because i stopped it now, and just proving that i can run this program on my server.)
but sometimes the twitch status shows i'm not watching the stream, and the time does not increase, and i opened my chrome on windows and watched for 5mins, it increased, not twitch's problem, so, does this program not working on server?
![image](https://user-images.githubusercontent.com/38283893/114741315-37f1d300-9d7d-11eb-91d0-e69f3bad8e7b.png)

**Comment by SekiBetu** [comment]
my server has a different IP, is this the reason why sometimes it shows i'm not watching because i opened the twitch page with my own IP? it stopped the program's watching action?

**Comment by AlexSterk** [comment]
I honestly don't know how Twitch measures watch time. If I knew I could probably make the tool a lot more accurate.

It could be that your IP is wrong. But another thing I can think of is that your server can't play the video stream in Chrome? Or maybe it only works on Windows, I haven't tried it anywhere else...

If it's possible, you can try the `--no-headless` option and seeing if Chrome is actually running the video stream. Or, if your server is not capable of having like a desktop environment, try editing the code yourself to take some screenshots and look at them and see if the stream is playing or not?

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/114767289-063b3500-9d9a-11eb-9abb-8d032c2d06e4.png)
must be the IP problem, i started the program on local machine, it's working now, so, the cookie may binded to the IP
