### ISSUE TITLE
about add new feature

### ISSUE THREAD

**Issue by MurasameCyan** [AlexSterk/TwitchDropGrabber#12]
enable channel loop check <-l time><-loop time>
set a time to check whether the channel online, if online end loop and start watch

**Comment by AlexSterk** [comment]
Just use the list (`-l`) and timeout (`-t`) together

**Comment by MurasameCyan** [comment]
> Just use the list (`-l`) and timeout (`-t`) together

check every 15 minutes '-f file -t 900000'   
like this?

**Comment by AlexSterk** [comment]
Yeah that should work. If it doesn’t it might be a bug

**Comment by MurasameCyan** [comment]
> Yeah that should work. If it doesn’t it might be a bug

ok i'll try thank you
