### ISSUE TITLE
-p bug?

### ISSUE THREAD

**Issue by MurasameCyan** [AlexSterk/TwitchDropGrabber#13]
![image](https://user-images.githubusercontent.com/50967145/115088091-05dd9e00-9f42-11eb-9443-5284e86a2afd.png)
![image](https://user-images.githubusercontent.com/50967145/115087783-70420e80-9f41-11eb-9837-345e832ec87b.png)
![image](https://user-images.githubusercontent.com/50967145/115088112-11c96000-9f42-11eb-8c2e-1ee149c50fdb.png)

socks error / http ok

proxy use in 
Qv2ray 2.7.0-pre2:6150 https://github.com/Qv2ray/Qv2ray
2021/04/17 05:54:11 tcp:127.0.0.1:13162 rejected  proxy/socks: unknown Socks version: 67
2021/04/17 05:54:15 tcp:127.0.0.1:13167 rejected  proxy/socks: unknown Socks version: 67
2021/04/17 05:54:18 tcp:127.0.0.1:13172 rejected  proxy/socks: unknown Socks version: 67

**Comment by AlexSterk** [comment]
Try `20810` as port: Don't use the socks proxy but the HTTP one?

Or maybe try `socks5://<IP>:<port>`

I don't know anything about proxies

**Comment by MurasameCyan** [comment]
> Try `20810` as port: Don't use the socks proxy but the HTTP one?
> 
> Or maybe try `socks5://<IP>:<port>`
> 
> I don't know anything about proxies

![image](https://user-images.githubusercontent.com/50967145/115090194-d0877f00-9f46-11eb-8365-0ca2a4b4ed4a.png)

ok! thank you
