### ISSUE TITLE
navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by SekiBetu** [AlexSterk/TwitchDropGrabber#15]
![image](https://user-images.githubusercontent.com/38283893/115453564-5dd21880-a252-11eb-9cb2-22b53618615a.png)
sometimes this error happens, and the program just stuck.

**Comment by SekiBetu** [comment]
https://github.com/AlexSterk/TwitchDropGrabber/blob/master/src/index.ts#L50

I've searched about this issue, and found out that disabling the timeout seems a solution, am i doing it right?
Will there be any side effects if the timeout is disabled? like, stuck forever?
```js
waitUntil: ['networkidle2', 'domcontentloaded'], timeout: 0
```

**Comment by SekiBetu** [comment]
I'm considering not to disable the timeout, but having crontab restart the program every hour if this issue can't be solved.

**Comment by AlexSterk** [comment]
I think if the timeout is exceeded during navigation that would indicate some kind of network issues. But you are of course welcome to try your fix (just edit the source code).

**Comment by SekiBetu** [comment]
I tested it for a few hours, indeed there is no more timeout issue, and seems no side effects.
