### ISSUE TITLE
-F not watching appoint game

### ISSUE THREAD

**Issue by MurasameCyan** [AlexSterk/TwitchDropGrabber#16]
![image](https://user-images.githubusercontent.com/50967145/115813999-d4c00a80-a426-11eb-8283-c0d45311c828.png)
![image](https://user-images.githubusercontent.com/50967145/115814038-e86b7100-a426-11eb-80af-0012934e4ff8.png)

can fix it?

**Comment by AlexSterk** [comment]
Just tried to fix this in the dev branch, try that one!

**Comment by MurasameCyan** [comment]
> Just tried to fix this in the dev branch, try that one!

![image](https://user-images.githubusercontent.com/50967145/115901271-88f77a80-a493-11eb-9548-389dae574258.png)

**Comment by AlexSterk** [comment]
Strange, it works fine for me. Could it be that the machine/network you run this on is slow? You can try editing the source code to increase the timeout: 

Change line 104 from 
` const gameLink = await page.waitForSelector('a[data-a-target="stream-game-link"]');`
to
`const gameLink = await page.waitForSelector('a[data-a-target="stream-game-link"]', {timeout: 0});`

and build again

**Comment by MurasameCyan** [comment]
> Strange, it works fine for me. Could it be that the machine/network you run this on is slow? You can try editing the source code to increase the timeout:
> 
> Change line 104 from
> ` const gameLink = await page.waitForSelector('a[data-a-target="stream-game-link"]');`
> to
> `const gameLink = await page.waitForSelector('a[data-a-target="stream-game-link"]', {timeout: 0});`
> 
> and build again

i use in Google Cloud Platform only dev -f get timeout

**Comment by MurasameCyan** [comment]
![image](https://user-images.githubusercontent.com/50967145/115922299-4f346d00-a4af-11eb-8815-25fc596d4db2.png)
maybe is work, i'll cheak again in channel online
---
it's work thx fix
