### ISSUE TITLE
how can set this timeout ?

### ISSUE THREAD

**Issue by MurasameCyan** [AlexSterk/TwitchDropGrabber#18]
![image](https://user-images.githubusercontent.com/50967145/115980188-226e7b80-a5bd-11eb-92b4-3ba62eebe005.png)

i try use 'npm start -- -t 600000 -g "Enlisted"'  without effect

**Comment by AlexSterk** [comment]
that timeout is how often it checks, it's not related to the timeout for browsing. If that timeout is reached it can mean that the internet is slow
