### ISSUE TITLE
[Ubisoft's Problem]Claiming Drops issue

### ISSUE THREAD

**Issue by SekiBetu** [AlexSterk/TwitchDropGrabber#21]
![image](https://user-images.githubusercontent.com/38283893/121790196-6a9a3980-cc0f-11eb-97ab-b37573b6fdd3.png)
![image](https://user-images.githubusercontent.com/38283893/121790235-dc728300-cc0f-11eb-8120-5d8d18da7fd3.png)
![image](https://user-images.githubusercontent.com/38283893/121790200-856cae00-cc0f-11eb-90f5-f9c3196dcaba.png)
![image](https://user-images.githubusercontent.com/38283893/121790215-adf4a800-cc0f-11eb-8f40-0d3d0d880d0a.png)

it seems Ubisoft's potato server just went down, and it effected other drops's claiming process, i just claimed the PUBG's twitch drop by myself
Is there a way to get all drops in rotation instead of getting stuck on uncollectable drops?

**Comment by AlexSterk** [comment]
I've pushed a possible fix. I don't have any rewards to claim so I can't test it, but please try it out and let me know. It's in the dev branch. 

Or you can checkout the commit directly. it's 86c9418 (listed above in this thread ^)

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/121812625-1b99e600-cc9b-11eb-8404-029a715f668e.png)
Roger, I'm testing it and if Don't Starve Together's drops can be successfully claimed, then it is working

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/121815732-6a02b100-ccaa-11eb-9322-594389657c4d.png)
It's working.

**Comment by AlexSterk** [comment]
Thanks for helping me test it!
