### ISSUE TITLE
Stuck at "Finding online channel..."

### ISSUE THREAD

**Issue by homever** [AlexSterk/TwitchDropGrabber#23]
Thank you for making this utility. 
The issue I met is whenever I start a twitch drop from CMD, it always ends up with "Finding online channel...". I know little about coding. Can you walk me through this? Thank you.

The internet is perfect.
![image](https://user-images.githubusercontent.com/3777914/122155564-ced02e00-ce99-11eb-91b7-24d439c07eeb.png)

**Comment by AlexSterk** [comment]
Try it with the `-v` option for more verbose logging. I think it did find a channel it just doesn't log it until after the first timeout (default 5 minutes)

**Comment by homever** [comment]
For some reason it is working fine now. I changed nothing which is quite odd. It has bothered me for a while. Guess I should've come with issue earlier. Thanks!

**Comment by homever** [comment]
This happens again. Here's the more verbose output.
![image](https://user-images.githubusercontent.com/3777914/122497007-4bd8e000-d01f-11eb-9970-3c1c55e8e434.png)

Along with the debug output

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '[-v]',
1 verbose cli   "Don't Starve Together"
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle twitch-drop-grabber@2021.5.2-6.1~prestart: twitch-drop-grabber@2021.5.2-6.1
6 info lifecycle twitch-drop-grabber@2021.5.2-6.1~start: twitch-drop-grabber@2021.5.2-6.1
7 verbose lifecycle twitch-drop-grabber@2021.5.2-6.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle twitch-drop-grabber@2021.5.2-6.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Tools\TwitchDropGrabber-master\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\ideav\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;D:\Program Files\Java\jdk-12.0.1\bin;D:\Program Files\Java\jdk-12.0.1\jre\bin;C:\Program Files\nodejs\;C:\Users\ideav\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Users\ideav\AppData\Roaming\npm
9 verbose lifecycle twitch-drop-grabber@2021.5.2-6.1~start: CWD: E:\Tools\TwitchDropGrabber-master
10 silly lifecycle twitch-drop-grabber@2021.5.2-6.1~start: Args: [ '/d /s /c', `node dist/index.js "[-v]" "Don't Starve Together"` ]
11 silly lifecycle twitch-drop-grabber@2021.5.2-6.1~start: Returned: code: 1  signal: null
12 info lifecycle twitch-drop-grabber@2021.5.2-6.1~start: Failed to exec start script
13 verbose stack Error: twitch-drop-grabber@2021.5.2-6.1 start: `node dist/index.js "[-v]" "Don't Starve Together"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid twitch-drop-grabber@2021.5.2-6.1
15 verbose cwd E:\Tools\TwitchDropGrabber-master
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "[-v]" "Don't Starve Together"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error twitch-drop-grabber@2021.5.2-6.1 start: `node dist/index.js "[-v]" "Don't Starve Together"`
22 error Exit status 1
23 error Failed at the twitch-drop-grabber@2021.5.2-6.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by AlexSterk** [comment]
Remove the `"[]"` around `-v`. The square brackets just imply that it's optional

**Comment by homever** [comment]
> Remove the `"[]"` around `-v`. The square brackets just imply that it's optional

Thank you. I did, but it showed exactly the same output.
![image](https://user-images.githubusercontent.com/3777914/122975171-a7132580-d3c5-11eb-97ba-7acdc133014c.png)

**Comment by AlexSterk** [comment]
![image](https://user-images.githubusercontent.com/13663706/122977330-8e8b1700-d395-11eb-8ac3-4ebc8d00e34b.png)
It's not finding channels because there are no channels with drops enabled

**Comment by homever** [comment]
Ahhh, forgive me being silly.
