### ISSUE TITLE
How do i watch a specific streamer only?

### ISSUE THREAD

**Issue by crabbo1** [AlexSterk/TwitchDropGrabber#27]
Loot drop is only available watching the offical devstream of this game:https://www.twitch.tv/warframe
I know it has something to do with -file command
Can you make an example file of the -f (channel list option) ?
Help would be appreciated :)

**Comment by AlexSterk** [comment]
Just create a text file with warframe on the first line. save it, and use -f and the path to the file

![image](https://user-images.githubusercontent.com/13663706/131217231-cddb474e-531d-4bf6-8efa-c990bba77e56.png)
