### ISSUE TITLE
Claim fails and retry every 5 mins

### ISSUE THREAD

**Issue by Talaxy009** [AlexSterk/TwitchDropGrabber#34]
Seems like claim fails and retry every 5 mins, which forced me to claim on the twitch site.
The screenshot of the log is as follows: 
![log](https://user-images.githubusercontent.com/41264828/198842394-320bb64a-ac90-4c53-921e-ebea8c17b589.png)

**Comment by AlexSterk** [comment]
Hmmm, maybe Twitch changed something on their end. Would have to test this
for myself in order to figure it out. I'll look into it

Op za 29 okt. 2022 om 18:34 schreef Taozc ***@***.***>:

**Comment by AlexSterk** [comment]
Okay so it seems Twitch is cracking down on bots and have added checks that (for now) make it impossible for the tool to work. I will add a disclaimer but I can't fix it. Unfortunately

**Comment by Talaxy009** [comment]
Ok, sorry to hear that... and thanks for your work!
