### ISSUE TITLE
how can auto claim drops?

### ISSUE THREAD

**Issue by MurasameCyan** [AlexSterk/TwitchDropGrabber#5]
![image](https://user-images.githubusercontent.com/50967145/114299322-2befe200-9aed-11eb-8d88-3c87d33064df.png)

**Comment by AlexSterk** [comment]
You're gonna need to give me more information than this lol

**Comment by akirayoo** [comment]
> You're gonna need to give me more information than this lol

![image](https://user-images.githubusercontent.com/50967145/114347189-24851300-9b97-11eb-8e7b-1383b812f1e3.png)
why i can't auto claim drops? need some setting ?

**Comment by AlexSterk** [comment]
@akirayoo I got an email saying you replied but I don't see the reply. Did you delete it? Did you figure it out? It might be that you need to let the tool run a little while before it claims a drop. By default it checks every 5 minutes

**Comment by MurasameCyan** [comment]
> @akirayoo I got an email saying you replied but I don't see the reply. Did you delete it? Did you figure it out? It might be that you need to let the tool run a little while before it claims a drop. By default it checks every 5 minutes

yes,  i use dev branches can auto claim now,but my friend use master branches no this problem
so i deleted

**Comment by AlexSterk** [comment]
Alright, glad it worked!
