### ISSUE TITLE
not watching drops enabled channel

### ISSUE THREAD

**Issue by MurasameCyan** [AlexSterk/TwitchDropGrabber#6]
![image](https://user-images.githubusercontent.com/50967145/114299705-58a4f900-9aef-11eb-94e2-164d5da3075b.png)

![image](https://user-images.githubusercontent.com/50967145/114299650-09f75f00-9aef-11eb-8926-b3dc32cd6238.png)

**Comment by peakxl** [comment]
These channels does have drops enabled. It just doesn't show on the search page. Click into the channel and you will see the tag "Drops Enabled". 谢谢你的keylol教程 :D

**Comment by MurasameCyan** [comment]
> These channels does have drops enabled. It just doesn't show on the search page. Click into the channel and you will see the tag "Drops Enabled". 谢谢你的keylol教程 :D

![image](https://user-images.githubusercontent.com/50967145/114306343-4edebe00-9b0e-11eb-8a9c-99964ac16978.png)
![image](https://user-images.githubusercontent.com/50967145/114306351-5900bc80-9b0e-11eb-88bd-949e59ded801.png)
![image](https://user-images.githubusercontent.com/50967145/114306361-5ef69d80-9b0e-11eb-810c-66e8ec542a04.png)
no tag lol

https://www.twitch.tv/directory/game/GangV%20%7C%20Battle%20Royale?tl=c2542d6d-cd10-4532-919b-3d19f30a768b

**Comment by peakxl** [comment]
I believe your screen resolution might be the issue. 
![image](https://user-images.githubusercontent.com/22212040/114306573-71f07a00-9adc-11eb-9bfd-523349bda18a.png)
![image](https://user-images.githubusercontent.com/22212040/114306586-7d43a580-9adc-11eb-934d-18c0c68e1317.png)
Or you can search with the tag enabled.
![image](https://user-images.githubusercontent.com/22212040/114306608-93516600-9adc-11eb-88dd-3e1234466a50.png)

**Comment by MurasameCyan** [comment]
> I believe your screen resolution might be the issue.
> ![image](https://user-images.githubusercontent.com/22212040/114306573-71f07a00-9adc-11eb-9bfd-523349bda18a.png)
> ![image](https://user-images.githubusercontent.com/22212040/114306586-7d43a580-9adc-11eb-934d-18c0c68e1317.png)
> Or you can search with the tag enabled.
> ![image](https://user-images.githubusercontent.com/22212040/114306608-93516600-9adc-11eb-88dd-3e1234466a50.png)

oh...i can see this tag now...sorry

**Comment by AlexSterk** [comment]
You can always just let it run/watch the channel for 5 minutes and see if you get progress in https://twitch.tv/inventory to find out if a channel works. But I'm glad it's fixed for you
