### ISSUE TITLE
是否能增加读取列表功能?

### ISSUE THREAD

**Issue by MurasameCyan** [AlexSterk/TwitchDropGrabber#7]
![image](https://user-images.githubusercontent.com/50967145/114307672-4a68d400-9b13-11eb-8268-648362ea1e64.png)

某些游戏只有指定的频道才会有掉落(比如RUST和Krunker等)
把所有指定掉落的用户名放入一个列表里 然后用 -l 或者--list 参数启动?

**Comment by AlexSterk** [comment]
I can't read this

**Comment by MurasameCyan** [comment]
> I can't read this

sorry,.emmm..my english is so bad.xd

can u add read list function? some game drop is limit channel only (like Rust & Krunker)


`npm start -- -l filename or --list filename`


`<filename>`
`user1 or https://www.twitch.tv/user1`
`user2 or https://www.twitch.tv/user2`
`user3 or https://www.twitch.tv/user3`
`...`

**Comment by AlexSterk** [comment]
Seems like a good idea for a new feature. I'll see if I have time to add it later. If you need this right now there are some other projects to try, for example this one: https://github.com/D3vl0per/Twitch-watcher

That one doesn't actually claim the drops though. This is why I created my own project. You could theoretically run both of the projects. One to watch the channels and mine to claim the drops

**Comment by MurasameCyan** [comment]
> Seems like a good idea for a new feature. I'll see if I have time to add it later. If you need this right now there are some other projects to try, for example this one: https://github.com/D3vl0per/Twitch-watcher
> 
> That one doesn't actually claim the drops though. This is why I created my own project. You could theoretically run both of the projects. One to watch the channels and mine to claim the drops

thank you XD
