### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yxkline** [AlexSterk/TwitchDropGrabber#8]
npm start -- Tom%20Clancy's%20Rainbow%20Six%20Siege→npm start -- Tom%20Clancys%20Rainbow%20Six%20Siege
（Clancy's→Clancys）

![E_OD}I8`FD~EK$LH1~$CO6A](https://user-images.githubusercontent.com/80211538/114427379-9f791880-9bed-11eb-8996-3ac3b87c3110.png)

Correct code：npm start-Tom％20Clancy%27s％20Rainbow％20Six％20Siege
（Clancy's→Clancy%27s）
![Y9MU)%H0E2@@7@1X`8P(OMH](https://user-images.githubusercontent.com/80211538/114431155-c0436d00-9bf1-11eb-94b3-1ad2dda2d949.png)

**Comment by MurasameCyan** [comment]
npm start -- Tom%20Clancy"'"s%20Rainbow%20Six%20Siege

**Comment by AlexSterk** [comment]
How is this a bug?
