### ISSUE TITLE
about add this 3 new feature

### ISSUE THREAD

**Issue by MurasameCyan** [AlexSterk/TwitchDropGrabber#9]
"how many drops enabled online channel in this game"

&

"drops status"
![image](https://user-images.githubusercontent.com/50967145/114526441-9170d980-9c79-11eb-9d0a-869e1c5a478c.png)

&

"proxy support <-p ip:port>,<--proxy ip:port>"

**Comment by AlexSterk** [comment]
I don't plan on doing the first one but for the second one I could do when I find the time
